### ISSUE TITLE
在小米低端手机上会内存溢出

### ISSUE THREAD

**Issue by xiaozhao0331** [LuckyJayce/GuideHelper#9]
java.lang.OutOfMemoryError: Failed to allocate a 3283212 byte allocation with 1510556 free bytes and 1475KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:824)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:801)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:768)
	at com.koalareading.koalareading.myview.GuideHelper.GuideHelper.showIm(GuideHelper.java:302)
	at com.koalareading.koalareading.myview.GuideHelper.GuideHelper.send(GuideHelper.java:192)
	at com.koalareading.koalareading.myview.GuideHelper.GuideHelper.access$300(GuideHelper.java:45)
	at com.koalareading.koalareading.myview.GuideHelper.GuideHelper$2.run(GuideHelper.java:165)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5290)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by LuckyJayce** [comment]
是你show的view太大了
